<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath('js/jquery.inputmask.bundle.js'))
; ?>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Fill credit card info') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate("Processing payment of %s%s"), $amount, $currency); ?></p>
                <p><?php echo $this->translate('Please fill the fields'); ?></p>

                <div class="row">
                    <div class="col-sm-8 col-md-6 col-lg-6">
                        <?php echo $this->form($this->form) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
